-- Drop FK from SALE to STAFF
ALTER TABLE SALE DROP FOREIGN KEY `2`;

-- Change Emp_ID to VARCHAR
ALTER TABLE STAFF MODIFY Emp_ID VARCHAR(10) NOT NULL;
ALTER TABLE SALE MODIFY Emp_ID VARCHAR(10);
ALTER TABLE users MODIFY emp_id VARCHAR(10);

-- Update existing data to new format
UPDATE STAFF SET Emp_ID = 'EMP001' WHERE Emp_ID = '1';
UPDATE STAFF SET Emp_ID = 'EMP002' WHERE Emp_ID = '2';
UPDATE STAFF SET Emp_ID = 'EMP003' WHERE Emp_ID = '3';
UPDATE SALE SET Emp_ID = 'EMP001' WHERE Emp_ID = '1';
UPDATE SALE SET Emp_ID = 'EMP002' WHERE Emp_ID = '2';
UPDATE users SET emp_id = 'EMP001' WHERE emp_id = '1';
UPDATE users SET emp_id = 'EMP002' WHERE emp_id = '2';

-- Re-add FK constraints
ALTER TABLE SALE ADD CONSTRAINT FOREIGN KEY (Emp_ID) REFERENCES STAFF(Emp_ID) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT FOREIGN KEY (emp_id) REFERENCES STAFF(Emp_ID) ON DELETE SET NULL;

-- Auto-generate Emp_ID trigger for new staff
DELIMITER //
CREATE TRIGGER before_staff_insert
BEFORE INSERT ON STAFF
FOR EACH ROW
BEGIN
  IF NEW.Emp_ID IS NULL OR NEW.Emp_ID = '' THEN
    SET NEW.Emp_ID = CONCAT('EMP', LPAD((SELECT COUNT(*)+1 FROM STAFF), 3, '0'));
  END IF;
END;
//
DELIMITER ;
